###Register
Post http://localhost:3500/auth/register
Content-Type: application/json

{
    "username":"alirv13",
    "email":"manirmp135@gmail.com",
    "mobile":"484848",
    "password":"986986",
    "confirm_password":"986986"
}
