###Register
Post http://localhost:3500/auth/register
Content-Type: application/json

{
    "username":"ashi",
    "email":"ashi@gmail.com",
    "mobile":"484848",
    "password":"ashimashi12",
    "confirm_password":"ashimashi12"
}

###Login
Post http://localhost:3500/auth/login
Content-Type: application/json
Authorization: {{$dotenv TOKEN}}

{
    "username":"ashi",
    "password":"ashimashi12"
}
