###Register
Post http://localhost:3500/auth/register
Content-Type: application/json

{
    "username":"",
    "email":"manirmp135@gmail.com",
    "mobile":"484848",
    "password":"986986",
    "confirm_password":"986986"
}

###Login
Post http://localhost:3500/auth/login
Content-Type: application/json
Authorization: {{$dotenv TOKEN}}

{
    "username":"alirv13",
    "password":"986986"
}
